version: '3'

services:
  web:
    build:
      context: .
    image: django-web:latest
    command:
      /start
    volumes:
      - /app/.venv
      - .:/app:z
    ports:
      - "8000:8000"
    depends_on:
      - my-docker-postgres
    environment:
      CELERY_BROKER_URL: redis://my-docker-redis:6379/0
      DATABASE_URL: postgis://myprojectuser:1234@my-docker-postgres:5432/mydb

  celery:
    # Celery and Web can use the same image.
    # Reference the image from above.
    image: django-web:latest
    command:
      /start_celery
    volumes:
      - .:/app
    depends_on:
      - my-docker-postgres
      - my-docker-redis
      - web
    environment:
      CELERY_BROKER_URL: redis://my-docker-redis:6379/0
      DATABASE_URL: post:is://myprojectuser:1234@my-docker-postgres:5432/mydb


  my-docker-redis:
    # in .env_file
    # CELERY_BROKER_URL=redis://my-docker-redis:6379/0
    image: redis:7.2.4
    ports:
      - 6379
    depends_on:
      - my-docker-postgres

  my-docker-postgres:
    # Settings have to be reflected in .env file when running
    # DATABASE_URL=postgis://myprojectuser:1234@my-docker-postgres:5432/mydb
    image: postgis/postgis:16-3.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
      POSTGRES_USER: myprojectuser

# Note that after creating a volume, the above info cannot be changed. The volume has to be deleted, or a different volume
# name has to be used
volumes:
  postgres_data:
