site_name: Enetra
nav:
  - Home: index.md

theme:
  name: "mkdocs"

plugins:
- autorefs
- search
- mkdocstrings
- mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
