# Generated by Django 5.2.4 on 2025-11-14 13:50

from django.contrib.auth.models import User
from django.db import migrations
from django.conf import settings
import environ

def set_admin(apps, schema_editor):
    if User.objects.filter(is_superuser=True).exists():
        return
    env = environ.Env()
    env.read_env(str(settings.BASE_DIR / ".env"))
    password=env.str("DJANGO_ADMIN_PASSWORD")
    if password:
        User.objects.create_superuser("admin", password=password)

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_admin, reverse),
    ]
