# Generated by Django 5.2.4 on 2026-07-02 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251114_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('Fertig', 'Finished'), ('Fehlgeschlagen', 'Failed'), ('Gestartet', 'Running'), ('Wartet', 'Waiting')]),
        ),
    ]
