# Generated by Django 5.2.4 on 2026-06-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251114_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('Fertig', 'Finished'), ('Fehlgeschlagen', 'Failed'), ('Gestartet', 'Running'), ('Wartet', 'Waiting')]),
        ),
    ]
