# Generated by Django 5.2.4 on 2025-11-18 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_alter_area_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='internal_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
