# Generated by Django 5.2.4 on 2026-03-09 14:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0005_area_description_deleteditem_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True)),
                ('efficiency', models.FloatField(default=1.0)),
                ('power_installed', models.FloatField(blank=True, default=None, null=True)),
                ('power_min', models.FloatField(blank=True, default=None, null=True)),
                ('power_max', models.FloatField(blank=True, default=None, null=True)),
                ('capex', models.FloatField(blank=True, default=None, null=True)),
                ('opex', models.FloatField(blank=True, default=None, null=True)),
                ('carrier', models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl'), ('gas', 'Gas')])),
                ('efficiency_thermal', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Electrolyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True)),
                ('efficiency', models.FloatField(default=1.0)),
                ('power_installed', models.FloatField(blank=True, default=None, null=True)),
                ('power_min', models.FloatField(blank=True, default=None, null=True)),
                ('power_max', models.FloatField(blank=True, default=None, null=True)),
                ('capex', models.FloatField(blank=True, default=None, null=True)),
                ('opex', models.FloatField(blank=True, default=None, null=True)),
                ('efficiency_thermal', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuelCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True)),
                ('efficiency', models.FloatField(default=1.0)),
                ('power_installed', models.FloatField(blank=True, default=None, null=True)),
                ('power_min', models.FloatField(blank=True, default=None, null=True)),
                ('power_max', models.FloatField(blank=True, default=None, null=True)),
                ('capex', models.FloatField(blank=True, default=None, null=True)),
                ('opex', models.FloatField(blank=True, default=None, null=True)),
                ('efficiency_thermal', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True)),
                ('efficiency', models.FloatField(default=1.0)),
                ('power_installed', models.FloatField(blank=True, default=None, null=True)),
                ('power_min', models.FloatField(blank=True, default=None, null=True)),
                ('power_max', models.FloatField(blank=True, default=None, null=True)),
                ('capex', models.FloatField(blank=True, default=None, null=True)),
                ('opex', models.FloatField(blank=True, default=None, null=True)),
                ('carrier', models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(choices=[('electricity', 'Strom'), ('diesel', 'Diesel'), ('oil', 'Öl'), ('gas', 'Gas'), ('heat', 'Wärme'), ('h2', 'H2')])),
                ('feed_in', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['scenario', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Heating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True)),
                ('efficiency', models.FloatField(default=1.0)),
                ('power_installed', models.FloatField(blank=True, default=None, null=True)),
                ('power_min', models.FloatField(blank=True, default=None, null=True)),
                ('power_max', models.FloatField(blank=True, default=None, null=True)),
                ('capex', models.FloatField(blank=True, default=None, null=True)),
                ('opex', models.FloatField(blank=True, default=None, null=True)),
                ('carrier', models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl'), ('electricity', 'Strom')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Heatpump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True)),
                ('efficiency', models.FloatField(default=1.0)),
                ('power_installed', models.FloatField(blank=True, default=None, null=True)),
                ('power_min', models.FloatField(blank=True, default=None, null=True)),
                ('power_max', models.FloatField(blank=True, default=None, null=True)),
                ('capex', models.FloatField(blank=True, default=None, null=True)),
                ('opex', models.FloatField(blank=True, default=None, null=True)),
                ('heatsource', models.CharField(choices=[('air', 'Luft'), ('water', 'Wasser'), ('waste_air', 'Abwärme')])),
                ('mode', models.IntegerField(choices=[(1, 'Monovalent'), (2, 'Bivalent')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['scenario', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeseries', models.JSONField()),
                ('spec_load', models.FloatField(default=None)),
            ],
            options={
                'ordering': ['scenario', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(choices=[('electricity', 'Strom'), ('heat', 'Wärme'), ('h2', 'H2')])),
                ('efficiency_load', models.FloatField(default=1.0)),
                ('efficiency_store', models.FloatField(default=1.0)),
                ('capacity_installed', models.FloatField(blank=True, default=None, null=True)),
                ('capacity_min', models.FloatField(blank=True, default=None, null=True)),
                ('capacity_max', models.FloatField(blank=True, default=None, null=True)),
                ('capex', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['scenario', 'id'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='solar',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='solar',
            name='solar_unique_internal_id_per_scenario',
        ),
        migrations.AddField(
            model_name='solar',
            name='angle',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='solar',
            name='azimut',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AddField(
            model_name='solar',
            name='capex',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solar',
            name='efficiency',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='solar',
            name='opex',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solar',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solar',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solar',
            name='power_max',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solar',
            name='power_min',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solar',
            name='spec_power',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solar',
            name='surface_area_installed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solar',
            name='surface_area_max',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solar',
            name='surface_area_min',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chp',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area'),
        ),
        migrations.AddField(
            model_name='chp',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chp',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario'),
        ),
        migrations.AddField(
            model_name='chp',
            name='updated_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electrolyzer',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area'),
        ),
        migrations.AddField(
            model_name='electrolyzer',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electrolyzer',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario'),
        ),
        migrations.AddField(
            model_name='electrolyzer',
            name='updated_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelcell',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area'),
        ),
        migrations.AddField(
            model_name='fuelcell',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelcell',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario'),
        ),
        migrations.AddField(
            model_name='fuelcell',
            name='updated_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generator',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area'),
        ),
        migrations.AddField(
            model_name='generator',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generator',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario'),
        ),
        migrations.AddField(
            model_name='generator',
            name='updated_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grid',
            name='areas',
            field=models.ManyToManyField(to='ports.area'),
        ),
        migrations.AddField(
            model_name='grid',
            name='connected_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ports.grid'),
        ),
        migrations.AddField(
            model_name='grid',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grid',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario'),
        ),
        migrations.AddField(
            model_name='grid',
            name='updated_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heating',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area'),
        ),
        migrations.AddField(
            model_name='heating',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heating',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario'),
        ),
        migrations.AddField(
            model_name='heating',
            name='updated_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heatpump',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area'),
        ),
        migrations.AddField(
            model_name='heatpump',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heatpump',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario'),
        ),
        migrations.AddField(
            model_name='heatpump',
            name='updated_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='load',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area'),
        ),
        migrations.AddField(
            model_name='load',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='load',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario'),
        ),
        migrations.AddField(
            model_name='load',
            name='updated_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grid',
            name='timeseries',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ports.load'),
        ),
        migrations.AddField(
            model_name='solar',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ports.load'),
        ),
        migrations.AddField(
            model_name='loadtemplate',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loadtemplate',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario'),
        ),
        migrations.AddField(
            model_name='loadtemplate',
            name='updated_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='load',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.loadtemplate'),
        ),
        migrations.AddField(
            model_name='storage',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area'),
        ),
        migrations.AddField(
            model_name='storage',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storage',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario'),
        ),
        migrations.AddField(
            model_name='storage',
            name='updated_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='grid',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='grid_unique_internal_id_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='loadtemplate',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='loadtemplate_unique_internal_id_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='load',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='load_unique_internal_id_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='storage_unique_internal_id_per_scenario'),
        ),
    ]
