# Generated by Django 5.2.4 on 2026-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0006_chp_electrolyzer_fuelcell_generator_grid_heating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('building', 'Gebäudefläche'), ('open', 'Freifläche')], null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='usage',
            field=models.CharField(choices=[('pv', 'Photovolatik'), ('parking', 'Parkfläche'), ('green', 'Grünfläche'), ('office', 'Büro'), ('storage', 'Lager')], null=True),
        ),
    ]
