# Generated by Django 5.2.4 on 2026-03-23 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0007_area_area_type_area_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='usage',
            field=models.CharField(blank=True, choices=[('pv', 'Photovolatik'), ('parking', 'Parkfläche'), ('green', 'Grünfläche'), ('office', 'Büro'), ('storage', 'Lager')], null=True),
        ),
    ]
