# Generated by Django 5.2.4 on 2026-03-23 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0008_alter_area_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='usage',
            field=models.CharField(blank=True, choices=[('pv', 'Photovolatik'), ('parking', 'Parkfläche'), ('green', 'Grünfläche'), ('office', 'Büro'), ('storage', 'Lager')], default=None, null=True),
        ),
        migrations.CreateModel(
            name='ChangedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.scenario')),
                ('updated_user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scenario', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('internal_id', 'scenario'), name='changeditem_unique_internal_id_per_scenario')],
            },
        ),
    ]
