# Generated by Django 5.2.4 on 2026-03-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ports', '0009_alter_area_usage_changeditem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='changeditem',
            name='changeditem_unique_internal_id_per_scenario',
        ),
        migrations.AddField(
            model_name='changeditem',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
