# Generated by Django 5.2.4 on 2026-03-24 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0010_remove_changeditem_changeditem_unique_internal_id_per_scenario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chp',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='capex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='efficiency',
            field=models.FloatField(default=1.0, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='opex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='power_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='power_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='capex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='efficiency',
            field=models.FloatField(default=1.0, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='opex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='power_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='power_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='capex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='efficiency',
            field=models.FloatField(default=1.0, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='opex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='power_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='power_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='capex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='efficiency',
            field=models.FloatField(default=1.0, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='opex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='power_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='power_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='capex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='efficiency',
            field=models.FloatField(default=1.0, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='opex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='power_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='power_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='capex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='efficiency',
            field=models.FloatField(default=1.0, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='opex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='power_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='power_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='capex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='efficiency',
            field=models.FloatField(default=1.0, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='opex',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='power_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='power_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung'),
        ),
    ]
