# Generated by Django 5.2.4 on 2026-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0011_alter_chp_area_alter_chp_capex_alter_chp_efficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chp',
            name='carrier',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl'), ('gas', 'Gas')], verbose_name='Energieträger'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='efficiency_thermal',
            field=models.FloatField(default=1.0, verbose_name='Thermische Effizienz'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='efficiency_thermal',
            field=models.FloatField(default=1.0, verbose_name='Thermische Effizienz'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='carrier',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl')], verbose_name='Energieträger'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='carrier',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl'), ('electricity', 'Strom')], verbose_name='Energieträger'),
        ),
    ]
