# Generated by Django 5.2.4 on 2026-06-10 07:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0012_alter_chp_carrier_alter_chp_efficiency_thermal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chp',
            name='capex',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='efficiency_thermal',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='opex',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='power_installed',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='power_kw',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='power_max',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='power_min',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='capex',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='efficiency_thermal',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='opex',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='power_installed',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='power_kw',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='power_max',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='power_min',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='capex',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='efficiency_thermal',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='opex',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='power_installed',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='power_kw',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='power_max',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='power_min',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='capex',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='description',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='opex',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='power_installed',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='power_kw',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='power_max',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='power_min',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='capex',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='description',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='id',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='name',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='opex',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='power_installed',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='power_kw',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='power_max',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='power_min',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='capex',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='description',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='heatsource',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='id',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='name',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='opex',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='power_installed',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='power_kw',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='power_max',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='power_min',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='azimut',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='capex',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='opex',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='power_installed',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='power_kw',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='power_max',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='power_min',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='spec_power',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='surface_area_installed',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='surface_area_max',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='surface_area_min',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='capacity_installed',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='capacity_max',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='capacity_min',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='capex',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='efficiency_load',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='efficiency_store',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='updated_user',
        ),
        migrations.CreateModel(
            name='CHPTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung')),
                ('efficiency', models.FloatField(default=1.0, verbose_name='Effizienz')),
                ('power_installed', models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung')),
                ('power_min', models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung')),
                ('power_max', models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung')),
                ('capex', models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX')),
                ('opex', models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX')),
                ('carrier', models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl'), ('gas', 'Gas')], verbose_name='Energieträger')),
                ('efficiency_thermal', models.FloatField(default=1.0, verbose_name='Thermische Effizienz')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chp',
            name='chptemplate_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ports.chptemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ElectrolyzerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung')),
                ('efficiency', models.FloatField(default=1.0, verbose_name='Effizienz')),
                ('power_installed', models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung')),
                ('power_min', models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung')),
                ('power_max', models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung')),
                ('capex', models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX')),
                ('opex', models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX')),
                ('efficiency_thermal', models.FloatField(default=1.0, verbose_name='Thermische Effizienz')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='electrolyzer',
            name='electrolyzertemplate_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ports.electrolyzertemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FuelCellTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung')),
                ('efficiency', models.FloatField(default=1.0, verbose_name='Effizienz')),
                ('power_installed', models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung')),
                ('power_min', models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung')),
                ('power_max', models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung')),
                ('capex', models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX')),
                ('opex', models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX')),
                ('efficiency_thermal', models.FloatField(default=1.0)),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fuelcell',
            name='fuelcelltemplate_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ports.fuelcelltemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GeneratorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung')),
                ('efficiency', models.FloatField(default=1.0, verbose_name='Effizienz')),
                ('power_installed', models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung')),
                ('power_min', models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung')),
                ('power_max', models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung')),
                ('capex', models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX')),
                ('opex', models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX')),
                ('carrier', models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl')], verbose_name='Energieträger')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='generator',
            name='generatortemplate_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ports.generatortemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HeatingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung')),
                ('efficiency', models.FloatField(default=1.0, verbose_name='Effizienz')),
                ('power_installed', models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung')),
                ('power_min', models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung')),
                ('power_max', models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung')),
                ('capex', models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX')),
                ('opex', models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX')),
                ('carrier', models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl'), ('electricity', 'Strom')], verbose_name='Energieträger')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='heating',
            name='heatingtemplate_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ports.heatingtemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HeatpumpTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung')),
                ('efficiency', models.FloatField(default=1.0, verbose_name='Effizienz')),
                ('power_installed', models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung')),
                ('power_min', models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung')),
                ('power_max', models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung')),
                ('capex', models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX')),
                ('opex', models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX')),
                ('heatsource', models.CharField(choices=[('air', 'Luft'), ('water', 'Wasser'), ('waste_air', 'Abwärme')])),
                ('mode', models.IntegerField(choices=[(1, 'Monovalent'), (2, 'Bivalent')])),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='heatpump',
            name='heatpumptemplate_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ports.heatpumptemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SolarTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power_kw', models.FloatField(blank=True, default=None, null=True, verbose_name='Leistung')),
                ('efficiency', models.FloatField(default=1.0, verbose_name='Effizienz')),
                ('power_installed', models.FloatField(blank=True, default=None, null=True, verbose_name='Installierte Leistung')),
                ('power_min', models.FloatField(blank=True, default=None, null=True, verbose_name='Minimale Leistung')),
                ('power_max', models.FloatField(blank=True, default=None, null=True, verbose_name='Maximale Leistung')),
                ('capex', models.FloatField(blank=True, default=None, null=True, verbose_name='CAPEX')),
                ('opex', models.FloatField(blank=True, default=None, null=True, verbose_name='OPEX')),
                ('azimut', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('angle', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)])),
                ('spec_power', models.FloatField(blank=True, default=None, null=True)),
                ('surface_area_installed', models.FloatField(blank=True, default=None, null=True)),
                ('surface_area_min', models.FloatField(blank=True, default=None, null=True)),
                ('surface_area_max', models.FloatField(blank=True, default=None, null=True)),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ports.load')),
                ('updated_user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='solar',
            name='solartemplate_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ports.solartemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StorageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(choices=[('electricity', 'Strom'), ('heat', 'Wärme'), ('h2', 'H2')])),
                ('efficiency_load', models.FloatField(default=1.0)),
                ('efficiency_store', models.FloatField(default=1.0)),
                ('capacity_installed', models.FloatField(blank=True, default=None, null=True)),
                ('capacity_min', models.FloatField(blank=True, default=None, null=True)),
                ('capacity_max', models.FloatField(blank=True, default=None, null=True)),
                ('capex', models.FloatField(blank=True, default=None, null=True)),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='storage',
            name='storagetemplate_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ports.storagetemplate'),
            preserve_default=False,
        ),
    ]
