# Generated by Django 5.2.4 on 2026-06-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0013_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='changeditem',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='chptemplate',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='deleteditem',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='electrolyzer',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='electrolyzertemplate',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='fuelcell',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='fuelcelltemplate',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='generatortemplate',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='grid',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='heatingtemplate',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='heatpump',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='heatpumptemplate',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='load',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='loadtemplate',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='solar',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='solartemplate',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='storagetemplate',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='is_template',
        ),
    ]
