# Generated by Django 5.2.4 on 2026-05-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0014_alter_deleteditem_options_alter_grid_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deleteditem',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='grid',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='load',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='loadtemplate',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'permissions': (('view', 'view scenario'), ('details', 'details scenario'), ('delete', 'delete scenario'), ('change', 'change scenario'))},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
    ]
