# Generated by Django 5.2.4 on 2026-06-22 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0014_remove_is_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chp',
            options={'ordering': ['scenario', 'id']},
        ),
        migrations.AlterModelOptions(
            name='electrolyzer',
            options={'ordering': ['scenario', 'id']},
        ),
        migrations.AlterModelOptions(
            name='fuelcell',
            options={'ordering': ['scenario', 'id']},
        ),
        migrations.AlterModelOptions(
            name='generator',
            options={'ordering': ['scenario', 'id']},
        ),
        migrations.AlterModelOptions(
            name='heating',
            options={'ordering': ['scenario', 'id']},
        ),
        migrations.AlterModelOptions(
            name='heatpump',
            options={'ordering': ['scenario', 'id']},
        ),
        migrations.AlterModelOptions(
            name='solar',
            options={'ordering': ['scenario', 'id']},
        ),
        migrations.AddConstraint(
            model_name='chp',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='chp_unique_internal_id_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='electrolyzer',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='electrolyzer_unique_internal_id_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='fuelcell',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='fuelcell_unique_internal_id_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='generator',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='generator_unique_internal_id_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='heating',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='heating_unique_internal_id_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='heatpump',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='heatpump_unique_internal_id_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='solar',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='solar_unique_internal_id_per_scenario'),
        ),
    ]
