# Generated by Django 5.2.4 on 2026-06-24 11:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0015_scenario_item_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
