# Generated by Django 5.2.4 on 2026-06-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0015_scenario_item_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'permissions': (('details', 'View area details'), ('delete', 'delete area'), ('change', 'change area'))},
        ),
        migrations.AlterModelOptions(
            name='chp',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='deleteditem',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='electrolyzer',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='fuelcell',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='generator',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='grid',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='heating',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='heatpump',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='load',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='loadtemplate',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'permissions': (('view', 'view scenario'), ('details', 'details scenario'), ('delete', 'delete scenario'), ('change', 'change scenario'))},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='solar',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item'))},
        ),
        migrations.RemoveConstraint(
            model_name='area',
            name='area_unique_internal_id_per_scenario',
        ),
    ]
