# Generated by Django 5.2.4 on 2026-07-06 14:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0016_alter_area_options_alter_chp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
