# Generated by Django 5.2.4 on 2026-06-30 08:36

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_data_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    password = settings.DATA_USER_PASSWORD  # None → unusable password
    username = settings.DATA_USER  # From .env file defaults to "data"
    User.objects.update_or_create(
        username=username,
        defaults={
            "password": make_password(password),
            "is_superuser": True,
            "is_staff": True,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ports", "0017_scenario_geom"),
    ]

    operations = [
        migrations.RunPython(create_data_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='scenario',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
