# Generated by Django 5.2.4 on 2026-06-30 08:36

import os

from django.contrib.auth.hashers import make_password
from django.db import migrations

def create_data_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    password = os.environ.get("DATA_USER_PASSWORD")  # None → unusable password
    User.objects.update_or_create(
        username="data",
        defaults={
            "password": make_password(password),
            "is_superuser": True,
            "is_staff": True,
            "is_active": True,
        },
    )



class Migration(migrations.Migration):

    dependencies = [
        ("ports", "0017_scenario_description_project_scenario_project"),
    ]

    operations = [
        migrations.RunPython(create_data_user, migrations.RunPython.noop),
    ]
