# Generated by Django 5.2.4 on 2026-08-31 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0019_scenario_description_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoadTemplate',
            new_name='Timeseries',
        ),
        migrations.RemoveConstraint(
            model_name='timeseries',
            name='loadtemplate_unique_internal_id_per_scenario',
        ),
        migrations.AddConstraint(
            model_name='timeseries',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='timeseries_unique_internal_id_per_scenario'),
        ),
    ]
