# Generated by Django 5.2.4 on 2026-07-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0019_alter_area_options_alter_chp_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view', 'view project'), ('details', 'details project'), ('delete', 'delete project'), ('change', 'change project'))},
        ),
    ]
