# Generated by Django 5.2.4 on 2026-09-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0019_scenario_description_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='task_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
