# Generated by Django 5.2.4 on 2026-08-31 12:07
"""Renaming the table from LoadTemplate does not rename some constraints and indecies
This leads to errrors when a new table called LoadTemplate is generated.
Here we rename these values to the new timeseries value
"""

from django.db import migrations

constraints = [
    "ports_loadtemplate_manager_id_0467f1bc_fk_auth_user_id",
    "ports_loadtemplate_scenario_id_66d6993a_fk_ports_scenario_id",
    "ports_loadtemplate_updated_user_id_e2ee8fea_fk_auth_user_id",
]


indexes = [
    "ports_loadtemplate_internal_id_2d4c50d8",
    "ports_loadtemplate_pkey",
    "ports_loadtemplate_manager_id_0467f1bc",
    "ports_loadtemplate_scenario_id_66d6993a",
    "ports_loadtemplate_updated_user_id_e2ee8fea",
]


def rename_index(old_index_name, new_index_name):
    return migrations.RunSQL(
        sql=f"""
                ALTER INDEX {old_index_name}
                RENAME TO {new_index_name}
            """,
        reverse_sql=f"""
                ALTER TABLE {new_index_name}
                RENAME TO {old_index_name}
            """,
    )


def rename_constraint(new_table_name, old_constraint_name, new_constraint_name):
    return migrations.RunSQL(
        sql=f"""
                ALTER TABLE public.{new_table_name}
                RENAME CONSTRAINT {old_constraint_name}
                TO {new_constraint_name};
            """,
        reverse_sql=f"""
                ALTER TABLE {new_table_name}
                RENAME CONSTRAINT {new_constraint_name}
                TO {old_constraint_name};
            """,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ports", "0020_rename_loadtemplate_timeseries_and_more"),
    ]

    operations = [
        rename_constraint(
            "ports_timeseries",
            constraint,
            constraint.replace("loadtemplate", "timeseries"),
        )
        for constraint in constraints
    ] + [
        rename_index(old_index, old_index.replace("loadtemplate", "timeseries"))
        for old_index in indexes
    ]
