# Generated by Django 5.2.4 on 2026-09-08 13:34

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0021_auto_20260831_1207'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['scenario', 'id'], 'permissions': (('details', 'View area details'), ('delete', 'delete area'), ('change', 'change area'))},
        ),
        migrations.AddField(
            model_name='chptemplate',
            name='internal_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='electrolyzertemplate',
            name='internal_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='fuelcelltemplate',
            name='internal_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='generatortemplate',
            name='internal_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='heatingtemplate',
            name='internal_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='heatpumptemplate',
            name='internal_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='solartemplate',
            name='internal_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='storagetemplate',
            name='internal_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='changeditem',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chp',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deleteditem',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heating',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='heatsource',
            field=models.CharField(choices=[('air', 'Luft'), ('water', 'Wasser'), ('waste_air', 'Abwärme')], null=True),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Monovalent'), (2, 'Bivalent')], null=True),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='heatsource',
            field=models.CharField(choices=[('air', 'Luft'), ('water', 'Wasser'), ('waste_air', 'Abwärme')], null=True),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Monovalent'), (2, 'Bivalent')], null=True),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solar',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, null=True, verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='carrier',
            field=models.CharField(choices=[('electricity', 'Strom'), ('heat', 'Wärme'), ('h2', 'H2')], null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='efficiency_load',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='efficiency_store',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='carrier',
            field=models.CharField(choices=[('electricity', 'Strom'), ('heat', 'Wärme'), ('h2', 'H2')], null=True),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='efficiency_load',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='efficiency_store',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('internal_id', 'scenario'), name='area_unique_internal_id_per_scenario'),
        ),
    ]
