# Generated by Django 5.2.4 on 2026-08-31 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0022_loadtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadtemplate',
            name='internal_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
