# Generated by Django 5.2.4 on 2026-09-17 11:23

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0022_alter_area_options_chptemplate_internal_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chp',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item')), 'verbose_name': 'Kraft-Wärme-Kopplung'},
        ),
        migrations.AlterModelOptions(
            name='chptemplate',
            options={'verbose_name': 'Kraft-Wärme-Kopplung Vorlage'},
        ),
        migrations.AlterModelOptions(
            name='electrolyzer',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item')), 'verbose_name': 'Elektrolyseur'},
        ),
        migrations.AlterModelOptions(
            name='electrolyzertemplate',
            options={'verbose_name': 'Elektrolyseur Vorlage'},
        ),
        migrations.AlterModelOptions(
            name='fuelcell',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item')), 'verbose_name': 'Brennstoffzelle'},
        ),
        migrations.AlterModelOptions(
            name='fuelcelltemplate',
            options={'verbose_name': 'Brennstoffzelle Vorlage'},
        ),
        migrations.AlterModelOptions(
            name='generator',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item')), 'verbose_name': 'Generator'},
        ),
        migrations.AlterModelOptions(
            name='generatortemplate',
            options={'verbose_name': 'Generator Vorlage'},
        ),
        migrations.AlterModelOptions(
            name='heating',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item')), 'verbose_name': 'Heizung'},
        ),
        migrations.AlterModelOptions(
            name='heatingtemplate',
            options={'verbose_name': 'Heizung Vorlage'},
        ),
        migrations.AlterModelOptions(
            name='heatpump',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item')), 'verbose_name': 'Wärmepumpe'},
        ),
        migrations.AlterModelOptions(
            name='heatpumptemplate',
            options={'verbose_name': 'Wärmepumpe Vorlage'},
        ),
        migrations.AlterModelOptions(
            name='solar',
            options={'verbose_name': 'Solaranlage'},
        ),
        migrations.AlterModelOptions(
            name='solartemplate',
            options={'verbose_name': 'Solaranlage Vorlage'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['scenario', 'id'], 'permissions': (('view', 'view item with limited attributes'), ('details', 'read item with all attributes'), ('delete', 'delete item'), ('change', 'change item')), 'verbose_name': 'Speicher'},
        ),
        migrations.AlterModelOptions(
            name='storagetemplate',
            options={'verbose_name': 'Speicher Vorlage'},
        ),
        migrations.RemoveConstraint(
            model_name='solar',
            name='solar_unique_internal_id_per_scenario',
        ),
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('building', 'Gebäudefläche'), ('open', 'Freifläche')], help_text='Art der Fläche.', null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text='Geometrie der Fläche.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='usage',
            field=models.CharField(blank=True, choices=[('pv', 'Photovolatik'), ('parking', 'Parkfläche'), ('green', 'Grünfläche'), ('office', 'Büro'), ('storage', 'Lager')], default=None, help_text='Nutzung der Fläche.', null=True),
        ),
        migrations.AlterField(
            model_name='changeditem',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='changeditem',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chp',
            name='area',
            field=models.ForeignKey(help_text='Fläche, der diese Komponente zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='carrier',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl'), ('gas', 'Gas')], help_text='Energieträger, der von der Kraft-Wärme-Kopplung genutzt wird.', verbose_name='Energieträger'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='chp',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='efficiency_thermal',
            field=models.FloatField(default=1.0, help_text='Thermischer Wirkungsgrad. Muss ein Wert zwischen 0 und 1 sein.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Thermische Effizienz'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chp',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='carrier',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl'), ('gas', 'Gas')], help_text='Energieträger, der von der Kraft-Wärme-Kopplung genutzt wird.', verbose_name='Energieträger'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='efficiency_thermal',
            field=models.FloatField(default=1.0, help_text='Thermischer Wirkungsgrad. Muss ein Wert zwischen 0 und 1 sein.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Thermische Effizienz'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='deleteditem',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='deleteditem',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='area',
            field=models.ForeignKey(help_text='Fläche, der diese Komponente zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='efficiency_thermal',
            field=models.FloatField(default=1.0, help_text='Thermischer Wirkungsgrad. Muss ein Wert zwischen 0 und 1 sein.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Thermische Effizienz'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='efficiency_thermal',
            field=models.FloatField(default=1.0, help_text='Thermischer Wirkungsgrad. Muss ein Wert zwischen 0 und 1 sein.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Thermische Effizienz'),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='area',
            field=models.ForeignKey(help_text='Fläche, der diese Komponente zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='efficiency_thermal',
            field=models.FloatField(default=1.0, help_text='Thermischer Wirkungsgrad. Muss ein Wert zwischen 0 und 1 sein.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='efficiency_thermal',
            field=models.FloatField(default=1.0, help_text='Thermischer Wirkungsgrad. Muss ein Wert zwischen 0 und 1 sein.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='area',
            field=models.ForeignKey(help_text='Fläche, der diese Komponente zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='carrier',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl')], help_text='Energieträger, der vom Generator genutzt wird.', verbose_name='Energieträger'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='carrier',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl')], help_text='Energieträger, der vom Generator genutzt wird.', verbose_name='Energieträger'),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='areas',
            field=models.ManyToManyField(help_text='Flächen, die an dieses Netz angeschlossen sind.', to='ports.area'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='carrier',
            field=models.CharField(choices=[('electricity', 'Strom'), ('diesel', 'Diesel'), ('oil', 'Öl'), ('gas', 'Gas'), ('heat', 'Wärme'), ('h2', 'H2')], help_text='Energieträger des Netzes.'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='connected_to',
            field=models.ForeignKey(blank=True, default=None, help_text='Netz, mit dem dieses Netz verbunden ist.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ports.grid'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='feed_in',
            field=models.BooleanField(default=False, help_text='Gibt an, ob dieses Netz Einspeisung unterstützt.'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='timeseries',
            field=models.ForeignKey(blank=True, default=None, help_text='Lastzeitreihe dieses Netzes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ports.load'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='area',
            field=models.ForeignKey(help_text='Fläche, der diese Komponente zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='carrier',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl'), ('electricity', 'Strom')], help_text='Energieträger, der von der Heizung genutzt wird.', verbose_name='Energieträger'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='heating',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heating',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='carrier',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('oil', 'Öl'), ('electricity', 'Strom')], help_text='Energieträger, der von der Heizung genutzt wird.', verbose_name='Energieträger'),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='area',
            field=models.ForeignKey(help_text='Fläche, der diese Komponente zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='heatsource',
            field=models.CharField(choices=[('air', 'Luft'), ('water', 'Wasser'), ('waste_air', 'Abwärme')], help_text='Wärmequelle der Wärmepumpe.', null=True),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Monovalent'), (2, 'Bivalent')], help_text='Betriebsart der Wärmepumpe (monovalent oder bivalent).', null=True),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='heatsource',
            field=models.CharField(choices=[('air', 'Luft'), ('water', 'Wasser'), ('waste_air', 'Abwärme')], help_text='Wärmequelle der Wärmepumpe.', null=True),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Monovalent'), (2, 'Bivalent')], help_text='Betriebsart der Wärmepumpe (monovalent oder bivalent).', null=True),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='load',
            name='area',
            field=models.ForeignKey(help_text='Fläche, der diese Last zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, to='ports.area'),
        ),
        migrations.AlterField(
            model_name='load',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='factor',
            field=models.FloatField(default=1.0, help_text='Skalierungsfaktor für die Werte der Zeitreihenvorlage. Muss größer oder gleich 0 sein.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='load',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='template',
            field=models.ForeignKey(help_text='Zeitreihenvorlage dieser Last.', on_delete=django.db.models.deletion.CASCADE, to='ports.timeseries'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung des Projekts.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(help_text='Name des Projekts.', null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung des Szenarios.', null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, help_text='Geografische Ausdehnung des Szenarios.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.TextField(help_text='Name des Szenarios.', null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solar',
            name='angle',
            field=models.FloatField(blank=True, default=None, help_text='Neigungswinkel der Solaranlage in Grad. Winkel muss ein Wert zwischen 0 und 90 betragen.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='solar',
            name='area',
            field=models.ForeignKey(help_text='Fläche, der diese Komponente zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, to='ports.area', verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='azimut',
            field=models.FloatField(blank=True, default=None, help_text='Ausrichtung der Solaranlage in Grad. Azimut muss ein Wert zwischen 0 und 360 betragen.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='solar',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='solar',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solar',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, help_text='Lastprofil der Solaranlage.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ports.load'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='spec_power',
            field=models.FloatField(blank=True, default=None, help_text='Spezifische Leistung der Solaranlage in kW/m². Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='solar',
            name='surface_area_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Fläche der Solaranlage in m². Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='solar',
            name='surface_area_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Fläche der Solaranlage in m². Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='solar',
            name='surface_area_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Fläche der Solaranlage in m². Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='angle',
            field=models.FloatField(blank=True, default=None, help_text='Neigungswinkel der Solaranlage in Grad. Winkel muss ein Wert zwischen 0 und 90 betragen.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='azimut',
            field=models.FloatField(blank=True, default=None, help_text='Ausrichtung der Solaranlage in Grad. Azimut muss ein Wert zwischen 0 und 360 betragen.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten der Komponente in €. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CAPEX'),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='efficiency',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad der Komponente. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Effizienz'),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='opex',
            field=models.FloatField(blank=True, default=None, help_text='Jährliche Betriebskosten der Komponente in €/a. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='OPEX'),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='power_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installierte Leistung'),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='power_kw',
            field=models.FloatField(blank=True, default=None, help_text='Nennleistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leistung'),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='power_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximale Leistung'),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='power_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Leistung der Komponente in kW. Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimale Leistung'),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, help_text='Lastprofil der Solaranlage.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ports.load'),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='spec_power',
            field=models.FloatField(blank=True, default=None, help_text='Spezifische Leistung der Solaranlage in kW/m². Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='surface_area_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Fläche der Solaranlage in m². Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='surface_area_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Fläche der Solaranlage in m². Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='surface_area_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Fläche der Solaranlage in m². Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='area',
            field=models.ForeignKey(help_text='Fläche, der dieser Speicher zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, to='ports.area'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='capacity_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Kapazität des Speichers (kWh oder Liter, abhängig vom Energieträger). Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='capacity_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Kapazität des Speichers (kWh oder Liter, abhängig vom Energieträger). Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='capacity_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Kapazität des Speichers (kWh oder Liter, abhängig vom Energieträger). Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten des Speichers (€/kWh oder €/l). Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='carrier',
            field=models.CharField(choices=[('electricity', 'Strom'), ('heat', 'Wärme'), ('h2', 'H2')], help_text='Energieträger des Speichers.', null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='efficiency_load',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad beim Beladen. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='efficiency_store',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad beim Entladen. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='capacity_installed',
            field=models.FloatField(blank=True, default=None, help_text='Installierte Kapazität des Speichers (kWh oder Liter, abhängig vom Energieträger). Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='capacity_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximale Kapazität des Speichers (kWh oder Liter, abhängig vom Energieträger). Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='capacity_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimale Kapazität des Speichers (kWh oder Liter, abhängig vom Energieträger). Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='capex',
            field=models.FloatField(blank=True, default=None, help_text='Investitionskosten des Speichers (€/kWh oder €/l). Muss größer oder gleich 0 sein.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='carrier',
            field=models.CharField(choices=[('electricity', 'Strom'), ('heat', 'Wärme'), ('h2', 'H2')], help_text='Energieträger des Speichers.', null=True),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='efficiency_load',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad beim Beladen. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='efficiency_store',
            field=models.FloatField(default=1.0, help_text='Wirkungsgrad beim Entladen. Muss ein Wert zwischen 0 und 1 sein.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='name',
            field=models.TextField(help_text='Name der Vorlage.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='spec_load',
            field=models.FloatField(default=None, help_text='Spezifische Last der Zeitreihe.'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='timeseries',
            field=models.JSONField(help_text='Zeitreihendaten.'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung der Vorlage.', null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(help_text='Hochgeladene Datei.', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.TextField(help_text='Name der Datei.', null=True),
        ),
    ]
