# Generated by Django 5.2.4 on 2026-09-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0023_alter_chp_options_alter_chptemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='changeditem',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='chp',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='chptemplate',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='deleteditem',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='electrolyzertemplate',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fuelcell',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fuelcelltemplate',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generatortemplate',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='heating',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='heatingtemplate',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='heatpumptemplate',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='load',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='solar',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='solartemplate',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='storagetemplate',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='name',
            field=models.TextField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
