# Generated by Django 5.2.4 on 2026-09-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0024_alter_area_name_alter_changeditem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='carrier',
            field=models.CharField(choices=[('electricity', 'Strom'), ('diesel', 'Diesel'), ('oil', 'Öl'), ('gas', 'Gas'), ('heat', 'Wärme'), ('h2', 'H2')], default='electricity', help_text='Energieträger des Netzes.'),
        ),
    ]
