from django.urls import path

from . import views  # noqa

app_name = "ports"

urlpatterns = [
    path(
        "",
        views.home,
        name="home",
    ),
    path(
        "<uuid:scenario_internal_id>/",
        views.enetra_tool,
        name="enetra_tool",
    ),
    path(
        "template_upload_from_load/<uuid:scenario_internal_id>/<str:model>/",
        views.template_upload_from_load,
        name="template_upload_from_load",
    ),
    path(
        "details_create/<uuid:scenario_internal_id>/<str:model>/",
        views.DetailsView.as_view(created=True),
        name="details_create",
    ),
    path(
        "changes_count/<uuid:scenario_internal_id>/",
        views.changes_count,
        name="changes_count",
    ),
    path(
        "patch_area/<uuid:scenario_internal_id>/",
        views.patch_area,
        name="patch_area",
    ),
    path(
        "changes/<uuid:scenario_internal_id>/",
        views.changes,
        name="changes",
    ),
    path(
        "geometries/<uuid:scenario_internal_id>/",
        views.geometries,
        name="geometries",
    ),
    path(
        "details/<uuid:scenario_internal_id>/<str:model>/",
        views.DetailsView.as_view(created=False),
        name="details",
    ),
    path(
        "create_project/",
        views.create_project,
        name="create_project",
    ),
    path(
        "create_scenario/<uuid:scenario_internal_id>/",
        views.create_scenario,
        name="create_scenario",
    ),
    path(
        "api/<str:model>/<uuid:internal_id>/",
        views.ApiView.as_view(),
        name="api",
    ),
    path(
        "api/<uuid:project_internal_id>/<str:email>/remove_project_user/",
        views.remove_project_user,
        name="api_remove_project_user",
    ),
    path(
        "api/<str:signed_invite_id>/remove_project_invite/",
        views.remove_project_invite,
        name="api_remove_project_invite",
    ),
    path(
        "api/<str:model>/<uuid:internal_id>/duplicate/",
        views.ApiView.as_view(action="duplicate"),
        name="api_duplicate",
    ),
    path(
        "api/loadtemplate/<uuid:scenario_internal_id>/<uuid:internal_id>/",
        views.api_load_template,
        name="api_load_template",
    ),
    path(
        "debug/switch-user/<str:username>/",
        views.debug_switch_user,
        name="debug_switch_user",
    ),
]
