from django.urls import path

from . import views  # noqa

app_name = "ports"

urlpatterns = [
    path(
        "",
        views.home,
        name="home",
    ),
    path(
        "<uuid:scenario_internal_id>/",
        views.enetra_tool,
        name="enetra_tool",
    ),
    path(
        "simulate/",
        views.testview,
        name="test",
    ),
    path(
        "timeseries_upload_from_load/<uuid:scenario_internal_id>/<str:model>/",
        views.timeseries_upload_from_load,
        name="timeseries_upload_from_load",
    ),
    # two paths each for the templates, so the scenario can be inside the context.
    # For normal swaps the scenario might not be necessary, since templates dont belong to scenarios
    path(
        "template_create/<str:model>/<uuid:scenario_internal_id>/",
        views.ObjectTemplatesView.as_view(created=True),
        name="template_create",
    ),
    path(
        "template_create/<str:model>/",
        views.ObjectTemplatesView.as_view(created=True),
        name="template_create",
    ),
    path(
        "templates/<str:model>/<uuid:scenario_internal_id>/",
        views.ObjectTemplatesView.as_view(created=False),
        name="templates",
    ),
    path(
        "templates/<str:model>/",
        views.ObjectTemplatesView.as_view(created=False),
        name="templates",
    ),
    path(
        "details_create/<uuid:scenario_internal_id>/<str:model>/",
        views.DetailsView.as_view(created=True),
        name="details_create",
    ),
    path(
        "changes_count/<uuid:scenario_internal_id>/",
        views.changes_count,
        name="changes_count",
    ),
    path(
        "patch_area/<uuid:scenario_internal_id>/",
        views.patch_area,
        name="patch_area",
    ),
    path(
        "changes/<uuid:scenario_internal_id>/",
        views.changes,
        name="changes",
    ),
    path(
        "geometries/<uuid:scenario_internal_id>/",
        views.geometries,
        name="geometries",
    ),
    path(
        "templateslist/",
        views.user_template_list,
        name="user_template_list",
    ),
    path(
        "details/<uuid:scenario_internal_id>/<str:model>/",
        views.DetailsView.as_view(created=False),
        name="details",
    ),
    path(
        "create_project/",
        views.create_project,
        name="create_project",
    ),
    path(
        "create_scenario/<uuid:scenario_internal_id>/",
        views.create_scenario,
        name="create_scenario",
    ),
    path(
        "api/<str:model>/<uuid:internal_id>/",
        views.ApiView.as_view(),
        name="api",
    ),
    path(
        "api/<str:model>/<uuid:internal_id>/duplicate/",
        views.ApiView.as_view(action="duplicate"),
        name="api_duplicate",
    ),
    path(
        "api/loadtemplate/<uuid:scenario_internal_id>/<uuid:internal_id>/",
        views.api_timeseries,
        name="api_timeseries",
    ),
    path(
        "debug/switch-user/<str:username>/",
        views.debug_switch_user,
        name="debug_switch_user",
    ),
]
